from pathlib import Path
import json

def p(text): return {'type':'p','text':text}
def h(text): return {'type':'h','text':text}
def box(label,text): return {'type':'box','label':label,'text':text}
def bullets(*items): return {'type':'bullets','items':items}
def table(headers,*rows): return {'type':'table','headers':headers,'rows':rows}
def page(title,lead,*blocks): return {'title':title,'lead':lead,'blocks':blocks}
def ref(*keys): return {'type':'refs','keys':keys}
D=[]
D.append({'file':'cahier_des_charges_cekarna.pdf','code':'01 / PRODUIT B2C','title':'Cahier des charges','subtitle':'Application web pour les personnes en recherche d’emploi','status':'PÉRIMÈTRE B2C ACTIF · PRODUIT EN DÉVELOPPEMENT','pages':[
page('Un assistant personnel pour chercher un emploi','Centraliser un profil confirmé, trouver des offres adaptées et préparer ses candidatures sans automatiser les décisions.',
h('Public et besoin prioritaires'),p('Cekarna s’adresse exclusivement aux particuliers en recherche d’emploi. Le produit aide une personne à structurer son profil, retrouver des annonces publiques, comprendre les correspondances avec son parcours et suivre ses démarches. Les entreprises, cabinets de recrutement, organisations et viviers de candidats sont hors périmètre.'),
box('PROPOSITION DE VALEUR','« Retrouvez des offres adaptées à votre profil, comprenez pourquoi elles sont proposées et gardez la maîtrise de chaque candidature. » Aucun emploi, entretien ou niveau de pertinence n’est garanti.'),
table(['Statut','Périmètre actuel'],['Livré dans le code','Application React, comptes et synchronisation, import de CV textuel avec preuves, recherche et suivi d’offres, comparaison expliquée, recommandations Hermes sobres et vérifiables, brouillons corrigibles, notifications et passkeys.'],['Avant lancement','France Travail réellement configuré, fournisseur email réel, hébergement HTTPS, secrets, sauvegardes, supervision et recette sur données autorisées.']),
h('Parcours principal'),p('Créer un compte → confirmer son adresse → compléter le profil ou importer un CV textuel → vérifier et corriger chaque information → rechercher ou demander des suggestions d’offres → ajouter volontairement une annonce au suivi → comparer, préparer puis exporter un brouillon.'),
p('Cekarna ne postule pas à la place de la personne, ne contacte pas une entreprise et ne transforme pas un niveau de correspondance en décision.')),
page('Fonctions et règles du produit','Une application B2C centrée sur le dossier privé de la personne.',
table(['Fonction','Comportement attendu'],['Compte','Inscription, vérification email, récupération, déconnexion, révocation de tous les appareils, suppression complète et passkeys facultatives comme second facteur.'],['Profil et CV','Saisie manuelle ou PDF textuel de 5 Mo et 10 pages maximum. Extraits sources visibles, correction obligatoire avant enregistrement ; aucun OCR ni valeur devinée.'],['Offres','Collecte depuis une liste de sources autorisées, normalisation, provenance, dates utiles et déduplication. France Travail reste désactivé sans identifiants et conditions acceptées.'],['Suggestions Hermes','Jusqu’à 100 offres préfiltrées localement ; au maximum 6 annonces compactes dans un seul appel. Au plus 5 suggestions avec extraits littéraux du profil et de l’offre.'],['Suivi','Ajout explicite, statuts, notes privées et rappels choisis. Une suggestion ne crée jamais une candidature.'],['Brouillons','Texte fondé sur les informations confirmées, modifiable et exportable. Aucun envoi intégré.']),
h('Comportements attendus'),bullets('Une modification du profil ou du lot d’offres change la clé de cache et produit une nouvelle analyse sur demande.','Une panne d’Hermes ou du collecteur laisse le profil, la recherche manuelle et le suivi accessibles.','Les conflits entre appareils montrent les deux choix avant tout écrasement.','Les résultats IA mentionnent le modèle et distinguent correspondance forte, possible ou à vérifier, sans probabilité d’embauche.'),
box('HORS PÉRIMÈTRE','Espace entreprise, ATS, vivier partagé, OCR, candidature automatique, messages envoyés automatiquement, paiement et abonnement tant que leur valeur et leur exploitation ne sont pas validées.')),
page('Données, sécurité et contrôle humain','Les données professionnelles servent l’assistance ; les coordonnées et notes privées restent hors des requêtes Hermes.',
h('Identité et isolation'),bullets('Le service d’identité Go utilise PostgreSQL, Redis, Argon2id, JWT Ed25519 courts et refresh opaques rotatifs. Les passkeys sont liées à l’origine et au RP ID ; leurs challenges expirent après cinq minutes.','Chaque import et chaque dossier synchronisé sont rattachés au compte contrôlé côté serveur. Un identifiant fourni par le navigateur ne suffit pas.','La récupération du mot de passe supprime toutes les passkeys et révoque les sessions. La suppression du compte purge les données rattachées ou refuse clairement si un service dépendant est indisponible.','Les secrets, jetons, CV, destinataires et contenus de message ne doivent pas apparaître dans les journaux.'),
h('Traitement optimisé avec Hermes'),p('Le PDF brut n’est pas transmis au modèle. NestJS compacte uniquement poste, ville, contrat, compétences, résumé, expériences et formations confirmés. Un préfiltre textuel traite au plus 100 offres, puis un appel unique présente au plus 6 candidates à Hermes avec un contexte borné. Les appels identiques sont regroupés, le résultat est réutilisé 15 minutes et chaque compte est limité à 6 nouvelles analyses par fenêtre.'),
h('Aucune information inventée'),p('Une recommandation n’est affichée que si Hermes recopie un extrait du profil et un extrait de l’annonce correspondante. Le serveur écarte les identifiants inconnus, les preuves absentes des données et les doublons. Une absence d’information reste inconnue. La personne relit l’annonce complète et choisit seule de l’ajouter à son suivi.'),
h('Information et conformité'),p('Les pages légales décrivent les traitements prévus. Avant publication, renseigner l’éditeur réel, les contacts, les prestataires, les régions, les durées de conservation et la procédure d’exercice des droits, puis faire revalider le cadre applicable à l’usage B2C réel par une personne compétente. [CNIL]'),ref('CNIL')),
page('Recette et conditions de lancement','Les validations locales prouvent le comportement du code testé, pas la disponibilité d’un service de production.',
table(['Étape','Preuve attendue'],['G1 · parcours local','Compte, CV, profil, recherche, suggestions, suivi, brouillon, export, récupération et suppression fonctionnent sur données fictives ou autorisées.'],['G2 · sources réelles','France Travail et email transactionnel configurés hors dépôt ; réception, limites, erreurs, retraits et rebonds vérifiés.'],['G3 · préproduction','HTTPS, secrets privés, migrations, sauvegarde et restauration, supervision, procédures d’incident et retour applicatif testés.'],['G4 · pilote B2C','Parcours mobile, clavier et multiappareil observé ; extraction et suggestions évaluées sur un corpus séparé des exemples de réglage.'],['G5 · lancement','Résultats, limites, coûts, support, information utilisateur et responsabilités documentés.']),
h('Critères de recette'),bullets('Isolation : aucun accès croisé dans les tests d’import, de dossier, de session et de cache personnalisé.','CV : chaque valeur annoncée comme extraite correspond à un passage littéral ; fichiers invalides, scannés, chiffrés, trop grands ou expirés sont refusés clairement.','Suggestions : au plus 100 offres inspectées, 6 envoyées en un appel Hermes et 5 affichées ; toute preuve inventée ou liée à une autre offre est rejetée.','Sobriété : appels identiques regroupés et mis en cache 15 minutes ; au plus 6 analyses nouvelles par compte et par fenêtre.','Résilience : panne IA sans perte du dossier ; conflits de synchronisation résolus par un choix explicite ; restauration de sauvegarde réellement démontrée avant lancement.'),
p('Le corpus d’évaluation doit contenir des profils et offres fictifs ou autorisés, rester distinct des exemples utilisés pour régler les règles et consigner commit, modèle, paramètres, matériel, erreurs et corrections humaines. Ne publier aucun taux de pertinence avant cette mesure.'),
box('DÉFINITION DE TERMINÉ','Code, erreurs, isolation, absence d’invention, suppression, documentation et tests concordent. La production reste bloquée tant que les dépendances réelles et la recette d’exploitation ne sont pas validées.'),
p('Ce cahier B2C et la feuille de route du dépôt sont les références actives. Les quatre autres PDF historiques restent des archives B2B et ne définissent aucune fonction à développer.'))
]})
D.append({'file':'optimisation_cekarna_v1.pdf','code':'02 / PERFORMANCE','title':'Performance & coûts','subtitle':'Mesurer avant de dimensionner — préserver qualité et marge','status':'OBJECTIFS DE PILOTE · AUCUN BENCHMARK ACQUIS','pages':[
page('Définir la charge utile','La charge se décrit par opérations et volumes, pas par le seul nombre d’inscrits.',
table(['Scénario proposé','Dimensionnement du test'],['Pilote','3 cabinets, 2 à 10 recruteurs chacun, jusqu’à 1 000 profils par cabinet.'],['Interactif','20 sessions simulées ; montée à 10 requêtes/seconde pendant 15 minutes après échauffement.'],['Import simultané','3 lots de 100 PDF conformes aux limites de 10 Mo et 30 pages ; tailles réelles consignées.'],['IA','3 lots de 50 brouillons ; concurrence plafonnée et attente mesurée séparément du calcul.'],['Étape suivante','Rejouer à 10 fois le volume après réussite ; aucune extrapolation à 500 000 utilisateurs.']),
h('Objectifs internes initiaux'),bullets('API courante hors transfert et IA : p95 inférieur à 500 ms, moins de 1 % de réponses 5xx sous charge interactive.','Comparaison d’une mission avec 1 000 profils déjà indexés du cabinet : p95 inférieur à 2 secondes.','PDF textuel : traitement p95 inférieur à 60 secondes ; brouillon : p95 inférieur à 30 secondes. Mesurer aussi le délai total avec attente.','Navigation disponible pendant les imports ; progression et erreurs visibles.'),
box('RÈGLE DE PUBLICATION','Conserver date, commit, matériel, région, modèles, corpus et paramètres. Afficher p50, p95, taux d’échec et coût. Un résultat de laboratoire n’est pas une garantie de production.')),
page('Optimiser le pipeline dans le bon ordre','Réduire les traitements inutiles avant de changer d’infrastructure.',
h('1 · Ingestion une seule fois'),p('Calculer une empreinte dans le périmètre du cabinet, extraire texte puis profil. Réutiliser uniquement les sorties du même document et de la même version de parseur. Détecter les doublons sans mutualiser les viviers privés.'),
h('2 · Recherche puis justification'),p('Appliquer les critères professionnels explicites, puis combiner recherche textuelle et proximité sémantique. Comparer à une référence par mots-clés. Réserver l’IA générative à la synthèse des preuves et, si les mesures le justifient, à une réévaluation d’un petit ensemble. Aucun score n’est une probabilité de réussite.'),
h('3 · Stockage et cache'),p('PostgreSQL est proposé ; pgvector est une option. Vérifier rappel et temps avec filtres de cabinet : un index approximatif filtré peut retourner trop peu de résultats. Commencer par un calcul exact sur les petits viviers ; indexer selon les mesures. [VECTOR]'),
box('CACHE PERSONNALISÉ','Organisation + profil/version + mission/version + modèle + version de consigne + méthode. Contrôler les droits avant lecture. Ne jamais réutiliser une analyse individuelle provenant d’un autre cabinet.'),
h('4 · Travail asynchrone'),p('Un worker absorbe parsing et génération. Redis/BullMQ est proposé pour la file ; NestJS fournit une intégration. Limiter concurrence par cabinet et globale, réserver les quotas avant lancement et exposer l’attente. [QUEUE]'),ref('VECTOR','QUEUE')),
page('Économie unitaire avant abonnement','Simulation de gestion, sans tarif fournisseur ni prévision de ventes.',
box('FORMULES','Coût direct = inférence + extraction + stockage + infrastructure allouée + paiement + support variable.<br/>Contribution = revenu HT − coût direct.<br/>Taux de contribution = contribution / revenu HT.'),
table(['Exemple à 299 € HT/mois','Budget supposé'],['Inférence et extraction','18 €'],['Stockage et sauvegardes','4 €'],['Infrastructure allouée','12 €'],['Paiement : hypothèse, pas tarif fournisseur','6 €'],['Support : 30 min à 40 €/h','20 €'],['Total des coûts directs','60 €'],['Contribution avant frais fixes et acquisition','239 €, soit 79,9 %']),
p('Avec 3 000 € de coûts fixes mensuels supplémentaires, 13 abonnements de ce type les couvriraient (3 000 / 239, arrondi au supérieur). Ce n’est pas un seuil réel avant budget complet : rémunération, acquisition, remboursements, attrition et charges. Ne pas compter deux fois une charge déjà allouée.'),
h('Instrumentation commerciale'),bullets('Enregistrer coût et volume par traitement, modèle et cabinet sans contenu personnel dans les journaux.','Mesurer le coût par profil utilisable et par synthèse acceptée, pas seulement par appel IA.','Objectif proposé : contribution d’au moins 70 % ; alerte si les coûts directs dépassent 30 % du revenu HT.','Au quota, arrêter les nouvelles tâches coûteuses et garder lecture/export. Aucun dépassement facturé sans accord explicite.')),
page('Quand changer de taille ou de modèle','Un incident ne se résout pas automatiquement en ajoutant des machines.',
table(['Signal','Action avant migration'],['File trop longue','Limiter concurrence, identifier le fournisseur lent, répartir les workers.'],['SQL lent','Examiner plans, index, filtres et volumes ; comparer exact/approximatif.'],['IA coûteuse','Réduire contextes, réutiliser sorties valides, plafonner régénérations et comparer modèles.'],['Parsing CPU','Profiler, isoler le processus, mesurer une implémentation optimisée.'],['GPU envisagé','Comparer coût complet aux API pour plusieurs taux d’occupation à qualité égale.']),
h('API ou auto-hébergement'),p('Inclure GPU, inactivité, exploitation, supervision, redondance et secours. Le local évite une facturation au token externe mais mobilise matériel et énergie. Aucun gain ×10 ou ×50 sans test comparable. Évaluer licences et flux de données avant choix du modèle.'),
h('Résilience proposée'),bullets('Au plus 3 tentatives pour panne transitoire avec temporisation ; aucune reprise automatique pour fichier invalide ou quota épuisé.','Tâches idempotentes : une reprise ne crée pas un second résultat ni une seconde facturation. [JOBS]','RPO 24 h et RTO 4 h : objectifs internes à confirmer par restauration testée, pas SLA implicite.','Suivre ancienneté des jobs, coût, erreurs et fraîcheur. Chaque alerte désigne un responsable et une action.'),ref('JOBS'),
box('DÉCISION À CHAQUE PALIER','Poursuivre si qualité, isolation et coût restent acceptables. Sinon réduire le périmètre ou revoir le prix avant d’élargir les volumes.'))
]})
D.append({'file':'plan_b2b_saas_v1.pdf','code':'03 / COMMERCIAL','title':'Offre SaaS B2B','subtitle':'Vendre un résultat vérifiable, avec un pilote accompagné','status':'CIBLE RETENUE · PRIX ET QUOTAS À TESTER','pages':[
page('Positionnement et premier marché','Cible retenue : les cabinets de recrutement. Segment proposé : petites équipes spécialisées dans les métiers tech.',
h('Acheteur, utilisateur, déclencheur'),p('Acheteur : dirigeant du cabinet. Utilisateur : recruteur qui relit un vivier pour une mission. Déclencheur : plusieurs candidatures à comparer, critères répétés et besoin de présenter une sélection justifiée au client.'),
box('PROPOSITION DE VALEUR','« Cekarna vous aide à retrouver les compétences utiles dans vos CV et à préparer une sélection expliquée, avec les sources sous les yeux. Vous vérifiez et décidez. »'),
h('Différenciation à démontrer'),bullets('Affirmations reliées aux extraits des CV ; incertitudes visibles.','Vivier privé et travail exportable.','Critères modifiables, versions traçables et brouillons éditables.','Temps gagné et corrections mesurés pendant le pilote.'),
h('Qualification commerciale'),p('Rechercher des équipes disposant de CV utilisables et d’un processus observable. Écarter du premier pilote les demandes de remplacement complet d’ATS, scraping massif, installation sur site ou envoi automatique. Noter ces besoins sans les promettre.'),
box('ÉTAT À ANNONCER','Produit en développement : le socle API existe, le parcours métier reste à construire. Une démo sur données fictives est un prototype. Aucun témoignage, résultat chiffré ou logo client ne doit être inventé.')),
page('Une offre limitée et compréhensible','Grille expérimentale en euros HT, pour entretiens et devis pilotes ; ni prix de marché établi ni offre déjà publiée.',
table(['Offre','Inclus','Prix à tester'],['Pilote · 30 jours','1 cabinet, 3 comptes, 3 missions actives, 300 imports, 100 brouillons ; 2 séances de 45 min.','199 € une fois'],['Essentiel · mensuel','3 comptes, 5 missions actives, 500 imports/mois, 200 brouillons/mois, 5 000 profils stockés, 5 Go.','299 €/mois'],['Équipe · mensuel','10 comptes, 20 missions actives, 2 000 imports/mois, 800 brouillons/mois, 20 000 profils stockés, 20 Go.','699 €/mois']),
h('Définition des unités'),bullets('Import : fichier traité avec succès ou retraitement demandé après modification. Doublon réutilisé et échec technique non décomptés.','Brouillon : génération livrée. Une régénération demandée consomme une unité ; une reprise technique ne compte pas deux fois.','Comparaisons : 300 pour le pilote, 2 000/mois Essentiel, 10 000/mois Équipe. Une unité = une exécution mission/vivier, pas chaque candidat.','Pilote : 1 000 profils et 1 Go maximum. Les limites de 10 Mo et 30 pages par fichier valent pour chaque offre.'),
p('Quotas non reportés. Alerter à 80 % et 100 % ; au plafond, bloquer les nouvelles opérations concernées, pas la consultation. Aucun supplément automatique. Support hors périmètre chiffré séparément.'),
box('CONDITIONS PROPOSÉES','Pilote sans renouvellement automatique. Abonnements sans engagement annuel, résiliables pour la prochaine échéance. À la fin : export pendant 30 jours, puis suppression selon contrat et sauvegardes. Finaliser les conditions avant encaissement.')),
page('Un pilote qui produit une preuve','Observer les utilisateurs avant de lancer une vente autonome.',
table(['Étape','Livrable et mesure'],['Avant signature','Vérifier MVP, périmètre, droits sur données, contrat de traitement et support.'],['Jour 1','Fixer 3 missions et un corpus ; relever temps et qualité du processus habituel.'],['Semaine 1','Importer, corriger, comparer ; noter erreurs, abandon et questions.'],['Semaines 2–3','Comparer des tâches comparables avec/sans outil ; alterner l’ordre pour limiter l’apprentissage.'],['Jour 30','Restituer temps, corrections, pertinence, coûts et avis ; proposer ou non un abonnement.']),
h('Critères commerciaux proposés'),bullets('Activation : première sélection vérifiée et exportée dans les 48 h après onboarding.','Valeur : baisse médiane du temps de préparation d’au moins 30 %, sans baisse de qualité évaluée. Objectif, pas promesse.','Adoption : au moins 2 utilisateurs réalisent une tâche utile chaque semaine.','Décision : viser 2 conversions sur 3 pilotes, puis répéter sur une cohorte plus large ; ce faible échantillon ne valide pas le marché.'),
box('SI LE PILOTE ÉCHOUE','Identifier segment, qualité des données, précision, coût ou absence d’usage répété. Ajuster une hypothèse à la fois. Ne pas compenser un manque de valeur par davantage de fonctionnalités.')),
page('Acquisition, exploitation et marge','Une vente reproductible commence par une démonstration sobre et des coûts suivis.',
h('Acquisition proposée'),p('Lister 30 cabinets du segment, rechercher 10 entretiens puis 3 pilotes. Objectifs d’activité, pas conversions prédites. Mesurer le canal et le temps passé. Les prises de contact réelles restent des actions commerciales distinctes de ce document.'),
h('Démonstration de 15 minutes'),bullets('3 min : mission et fonctionnement actuel.','7 min : CV fictif, extraction, correction et comparaison sourcée.','3 min : brouillon, export, quotas et suppression.','2 min : limites et proposition de pilote si le besoin correspond.'),
h('Exploitation simple'),p('Onboarding assisté, guide court, canal email unique. Première réponse proposée sous 2 jours ouvrés, lundi à vendredi hors jours fériés français ; pas de support 24/7. En incident, qualifier accès aux données, panne ou usage bloqué et annoncer la prochaine mise à jour sans inventer un délai de résolution.'),
h('Facturation à construire'),p('Activer les droits après confirmation serveur du paiement, pas après redirection navigateur. Vérifier la signature des webhooks, dédupliquer et gérer les événements hors ordre. Tracer résiliation, paiement échoué et remboursement. [PAY]'),
p('Suivre revenu HT, contribution par cabinet, support et acquisition. Le document 02 illustre une contribution de 79,9 % ; ce n’est pas une marge constatée. Recalculer avec les usages réels.'),ref('PAY')),
page('Dossier de vente et lancement','Pouvoir expliquer ce qui est livré, comment cela fonctionne et ce qui se passe en cas de problème.',
table(['Pièce','Condition de validation'],['Fiche produit','Fonctions disponibles, limites, prérequis et captures fidèles.'],['Proposition pilote','Prix, durée, unités, corpus, accompagnement, recette et sortie.'],['Dossier données','Rôles, contrat, prestataires, régions, rétention et droits.'],['Dossier IA','Usage, risques, évaluation, supervision et qualification réglementaire.'],['Guide client','Import, correction, preuves, export et suppression.'],['Exploitation','Responsables, restauration testée, support, paiement et incidents.']),
h('Formulations commerciales'),p('Employer « sélection expliquée à partir de vos documents », « validation par le recruteur » et « quotas transparents ». Un gain de temps publié précise contexte et échantillon, avec accord des clients concernés.'),
h('Promesses à retirer'),p('« Recrutement sans biais », « 100 % conforme », « placement garanti », « illimité », « coût presque nul » ou « souverain » sans preuve sur tous les flux. Une région d’hébergement ne décrit pas le traitement de tous les prestataires.'),
box('GO / NO-GO','Abonnements après parcours validé, pilote concluant, coûts compatibles, support assuré et qualification données/IA documentée. Le cahier reste la référence des exigences ; ce plan ne vaut pas validation juridique.'),
p('Concentrer l’effort sur le SaaS B2B. La formation reste une offre future distincte, conditionnée à un parcours technique stabilisé.'))
]})
D.append({'file':'plan_formation_ia_v1.pdf','code':'04 / TRANSMISSION','title':'Formation & kit technique','subtitle':'Une offre complémentaire après stabilisation du SaaS','status':'OPTION FUTURE · NON PRIORITAIRE AU LANCEMENT','pages':[
page('Une seconde offre, un autre public','Le SaaS sert les recruteurs ; le kit s’adresse aux développeurs qui veulent reproduire un pipeline documentaire.',
box('DÉCISION DE PRIORITÉ','Ne pas produire la formation complète pendant le MVP B2B. Capturer notes et démonstrations ; décider de la vente après stabilisation et test auprès de 5 apprenants.'),
h('Résultat pédagogique'),p('Importer un CV fictif textuel, vérifier le profil extrait, comparer à une mission et générer une synthèse éditable avec sources. C’est un démonstrateur pédagogique, pas un SaaS multi-organisation prêt à exploiter.'),
h('Prérequis et configurations'),bullets('Git, npm et terminal ; bases de TypeScript et HTTP.','Documenter les versions réellement testées du système, de Node.js, du moteur de modèle et des dépendances.','Proposer un diagnostic matériel avant achat. Mémoire et vitesse dépendent du modèle et de sa quantification ; pas de GPU minimal universel annoncé.','Parcours local facultatif évalué séparément. Sans API distante, matériel et énergie restent à financer ; aucun débit garanti sur tout ordinateur.'),
h('Livrables'),p('Sources versionnées, données fictives, scripts, corrigés, journal des versions, dépannage et vidéos. Aucun CV réel, secret, identifiant client ni configuration de production.'),
p('Positionnement : « Construisez et évaluez un pipeline documentaire expliqué ». Retirer la promesse d’un agent fonctionnel en une journée avant observation du temps nécessaire chez les apprenants.')),
page('Programme orienté résultat','Chaque module termine par une preuve de réussite et une procédure de diagnostic.',
table(['Module','Exercice vérifiable'],['1 · Environnement','Installer le kit ; tests réussis et réponse /health.'],['2 · Ingestion','Lire un PDF fictif avec pages ; traiter fichier invalide ou scanné.'],['3 · Profil','Valider une structure typée ; corriger l’extraction et préserver les inconnus.'],['4 · Recherche','Comparer filtres et similarité sur missions annotées ; expliquer les résultats.'],['5 · Génération','Synthèse sourcée ; détecter sortie invalide et instruction malveillante dans un CV.'],['6 · Exploitation','Mesurer coût/latence, limiter reprises, supprimer les données et exporter.']),
h('Travail final'),p('Un rapport présente résultat, limites, temps et configuration. L’évaluation porte sur la reproductibilité et les preuves, pas sur une vidéo spectaculaire.'),
h('Collecte web facultative'),p('Utiliser un site d’exercice ou une source autorisée. Étudier limitations de débit et erreurs HTTP. Le kit ne dépend pas de contournements anti-bot ni de comptes de plateformes tierces.'),
box('RECETTE PÉDAGOGIQUE','Objectif : 4 apprenants sur 5 terminent avec la documentation, sans intervention en direct. Mesurer leur temps puis publier une estimation. Les tests doivent fonctionner sur chaque configuration annoncée.')),
page('Prix, maintenance et décision de vente','Hypothèses à tester ; la formation n’est pas produite ni commercialisée.',
table(['Offre','Périmètre','Prix à tester'],['Kit autonome','Vidéos, code, données fictives ; correctifs 12 mois et support installation email 30 jours.','199 € HT'],['Accompagné','Kit + 60 min individuelles, réservées sous 60 jours selon disponibilité ; pas de sur-mesure.','349 € HT']),
h('Viabilité illustrative'),p('50 heures de production à 40 €/h représentent 2 000 €, hors outils et maintenance. Avec 199 € HT par vente et 39 € de coûts variables supposés, contribution de 160 € : 13 ventes couvriraient 2 000 €. Aucune vente n’est prédite. Ajouter acquisition, remboursements et mises à jour au budget.'),
h('Conditions à préparer'),bullets('Définir licence du code, des modèles et des contenus ; ne pas céder implicitement la propriété du SaaS.','Préciser systèmes testés, coûts externes, correctifs et support ; pas de maintenance à vie.','Si vente aux particuliers, adapter présentation TTC, conditions et parcours de fourniture numérique avant publication.','Annoncer le traitement des éditions majeures et conserver leur historique.'),
box('DÉCLENCHEUR','Vendre si le kit est reproductible, les tests apprenants réussissent, le support reste soutenable et une demande payante est observée. Priorité au SaaS B2B.'),
p('Acquisition proposée : démo fictive, extrait gratuit et page avec prérequis/résultats. Utiliser uniquement des témoignages réels et autorisés.'))
]})
D.append({'file':'stack_microservices_rust_v1.pdf','code':'05 / ARCHITECTURE','title':'Architecture progressive','subtitle':'Un socle modulaire, des évolutions justifiées par les mesures','status':'NESTJS EXISTANT · SERVICES SPÉCIALISÉS CONDITIONNELS','pages':[
page('Partir du code réel','Remplacer une migration prématurée Rust/Go par une trajectoire de livraison et d’exploitation.',
table(['Brique','Statut et choix'],['API','Existant : NestJS 11, Express, TypeScript strict ; conserver.'],['Interface','À construire en TypeScript ; choix de framework à consigner avant création.'],['Données','Proposé : PostgreSQL, migrations et stockage objet privé.'],['Recherche','Proposé : SQL/textuel puis pgvector après évaluation. Pas de Qdrant initial.'],['Traitements','Proposé : worker Node.js et Redis/BullMQ lors de l’ajout du pipeline.'],['IA','Adaptateur fournisseur à choisir : délai, coût, schéma et versions. Hermes non requis au MVP.']),
box('FLUX DE RÉFÉRENCE','Interface → API et autorisations → stockage privé + job → worker d’extraction → profil validé → comparaison → brouillon → export demandé par le recruteur.'),
p('Les longues opérations retournent un identifiant de traitement ; l’interface suit son état. Aucune donnée brute dans la file si une référence protégée suffit.'),
h('Modules métier proposés'),p('identity, organizations, documents, profiles, missions, matching, drafts, usage et billing. Contrôleurs courts, règles dans les services, stockage et fournisseurs derrière des adaptateurs. Créer chaque module au moment de sa fonction.')),
page('Données et contrats durables','La cohérence des données prime sur un gain marginal de sérialisation.',
h('Modèle logique'),p('Organization et Membership définissent les accès. Document et ProfileVersion portent source et interprétation. MissionVersion fixe les critères. MatchResult et Draft référencent ces versions. Job et UsageEvent tracent exécution et consommation. Identifiants stables, dates et contraintes de relations entre données de la même organisation.'),
h('Isolation de bout en bout'),bullets('Déterminer l’organisation depuis une identité et une appartenance vérifiées ; contrôler requêtes, téléchargements et exports.','Propager l’organisation aux jobs, caches, vecteurs et fichiers. Un préfixe de stockage n’est pas une autorisation.','Tester identifiants devinés, recherche, reprise et export. Évaluer la sécurité SQL par ligne comme défense supplémentaire.','Vérifier le rappel vectoriel avec filtres de cabinet contre une recherche exacte. [VECTOR]'),
h('Publication fiable'),p('Créer le job durablement en base avec l’opération métier. Prévoir une boîte d’envoi transactionnelle si base et file peuvent diverger : un relais publie puis marque l’événement. La rediffusion reste possible ; le worker doit être idempotent. [JOBS]'),
box('VERSIONNER POUR EXPLIQUER','Un résultat référence document, profil, mission, modèle et méthode. Une modification produit une nouvelle version ; elle ne réécrit pas silencieusement une décision historique. Appliquer la rétention à cet historique.'),ref('VECTOR','JOBS')),
page('Déployer et diagnostiquer simplement','L’exploitation doit rester réalisable par l’équipe disponible.',
h('Environnements et livraison'),p('Séparer développement, préproduction et production. Le workflow CI du dépôt couvre lint, typage, tests et build ; exécution distante à activer sur le dépôt hébergé. Ajouter les tests métier avec les fonctions. API et worker déployables séparément, configuration externe et migrations compatibles avec retour applicatif.'),
h('Supervision'),bullets('Identifiant de corrélation entre requête, job et résultat ; journaux structurés sans CV ni jeton.','Mesurer erreurs, file, temps et coûts ; affecter chaque alerte à un responsable.','/health reste un contrôle de vie ; ajouter une readiness quand base et file existent.','Tester restauration et purge après changement du stockage.'),
h('Modes dégradés'),p('Une panne IA suspend la génération mais conserve la lecture. Pas de bascule vers un fournisseur non approuvé. Une panne de file est visible ; les jobs durables sont republiables. Un fichier invalide termine en erreur explicite, sans boucle de reprise.'),
box('DÉPLOIEMENT INITIAL PROPOSÉ','API et worker dans un environnement simple, données sauvegardées. Choisir hébergement et régions après budget et revue des flux. Kubernetes, NATS, gRPC et multi-région ne sont pas requis pour le pilote.'),
p('Objectifs internes du document 02 : RPO 24 h, RTO 4 h, à démontrer avant engagement. Préparer retour applicatif et compatibilité des migrations ; une sauvegarde n’est pas un rollback instantané.')),
page('Quand extraire un service','Une décision économique fondée sur un profilage reproductible.',
table(['Évolution','Condition avant décision'],['Parseur Rust','Parsing dominant le CPU malgré optimisation/isolement ; prototype mesuré sur le même corpus.'],['Orchestrateur Go','Limite de concurrence démontrée ; bénéfice supérieur au coût de maintenance.'],['Qdrant','Recherche insuffisante après réglage SQL/vectoriel ; comparaison qualité/coût avec filtres tenant.'],['GPU dédié','Coût complet inférieur à l’API à qualité égale et occupation prudente.'],['gRPC ou autre bus','Besoin non satisfait par HTTP + file ; gain supérieur au coût opératoire.']),
h('Dossier de décision'),p('Goulot, scénario, mesures avant/après, qualité, coûts, responsable, migration et retour arrière. Un langage compilé ne réduit pas automatiquement le temps du navigateur, du réseau ou d’un modèle distant.'),
h('Migration contrôlée'),bullets('Contrat versionné et tests communs ; une seule autorité d’écriture par donnée.','Comparer hors production puis sur petite cohorte, avec retour possible.','Rejouer isolation, suppression, quotas et idempotence.','Documenter délais, annulation et reprises ; ne pas promettre « exactement une fois » sans traiter les effets de bord.'),
box('CRITÈRE FINAL','Résoudre un problème mesuré sans dégrader preuves, isolation ou support. Cette trajectoire n’implique aucun service spécialisé déjà implémenté.'))
]})

sources={
'CNIL':{'label':'CNIL — Le guide du recrutement','url':'https://www.cnil.fr/fr/le-guide-du-recrutement'},
'AI':{'label':'Commission européenne — AI Act, usages à haut risque','url':'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai'},
'VECTOR':{'label':'pgvector — documentation officielle, index et filtres','url':'https://github.com/pgvector/pgvector'},
'QUEUE':{'label':'NestJS — files de traitement BullMQ','url':'https://docs.nestjs.com/techniques/queues'},
'JOBS':{'label':'BullMQ — tâches idempotentes','url':'https://docs.bullmq.io/patterns/idempotent-jobs'},
'PAY':{'label':'Stripe — webhooks, signatures et événements','url':'https://docs.stripe.com/webhooks'}
}

# Le cahier des charges est désormais la référence B2C active. Les quatre autres
# dossiers conservent leur contenu historique B2B / formation et leur marquage.
for index, document in enumerate(D):
    if index == 0:
        document['version'] = '3.0'
        document['date'] = '08 septembre 2026'
        document['archived'] = False
    else:
        document['subtitle'] = f"Archive historique — {document['subtitle']}"
        document['status'] = 'ARCHIVÉ · HORS PÉRIMÈTRE B2C'
        document['version'] = '2.0 archive'
        document['date'] = '07 septembre 2026'
        document['archived'] = True

payload={'version':'3.0','date':'08 septembre 2026','sources':sources,'documents':D}
if __name__=='__main__':
    target=Path(__file__).with_name('cekarna_v2.json')
    target.write_text(json.dumps(payload,ensure_ascii=False,indent=2),encoding='utf-8')
    print(f'{len(D)} documents, {sum(len(d["pages"]) for d in D)} pages: {target}')
